version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Updating system packages..."
      - yum update -y || echo "Warning: System update failed, continuing..."
      - echo "Installing required dependencies..."
      - yum install -y unzip aws-cli

  build:
    commands:
      - echo "Build phase - No compilation required"

  post_build:
    commands:
      - echo "Setting up application directory..."
      - mkdir -p /home/ec2-user/app
      - cp -r index.html /home/ec2-user/app/
      - cp -r scripts/ /home/ec2-user/app/ || echo "Warning: No scripts directory found, skipping..."

  deploy:
    commands:
      - echo "Starting application..."
      - chmod +x /home/ec2-user/app/scripts/start.sh || echo "Warning: No start script found, skipping execution..."
      - /home/ec2-user/app/scripts/start.sh || echo "Warning: Application may not have started properly."

artifacts:
  files:
    - index.html
    - scripts/**