version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Updating system packages..."
      - yum update -y || true
      - echo "Installing required dependencies..."
      - yum install -y unzip aws-cli || true

  pre_build:
    commands:
      - echo "Pre-build phase - No actions required"

  build:
    commands:
      - echo "Build phase - No compilation required"

  post_build:
    commands:
      - echo "Setting up application directory..."
      - mkdir -p /home/ec2-user/app
      - cp -r index.html /home/ec2-user/app/
      - if [ -d scripts ]; then cp -r scripts /home/ec2-user/app/; else echo "No scripts directory found, skipping..."; fi
      - echo "Starting application..."
      - if [ -f /home/ec2-user/app/scripts/start.sh ]; then 
          chmod +x /home/ec2-user/app/scripts/start.sh && /home/ec2-user/app/scripts/start.sh; 
        else 
          echo "No start script found, skipping execution."; 
        fi

artifacts:
  files:
    - index.html
    - scripts/**