version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing dependencies..."
      - ls -l   # List files to check if package.json is present
      - cat package.json   # Verify the package.json content
      - npm install
  build:
    commands:
      - echo "Building application..."
  post_build:
    commands:
      - echo "Zipping application for deployment..."
      - zip -r app.zip .
      - echo "Uploading to S3..."
      - aws s3 cp app.zip s3://my-new-backt/
      - echo "Build complete"

artifacts:
  files:
    - app.zip
  discard-paths: yes

