version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Updating system packages..."
      - sudo yum update -y || echo "Warning: Update failed, continuing..."
      - echo "Installing necessary dependencies..."
      - sudo yum install -y unzip aws-cli

  build:
    commands:
      - echo "Build phase - No compilation required"

  post_build:
    commands:
      - echo "Moving files to deployment directory..."
      - sudo mkdir -p /home/ec2-user/app
      - sudo cp -r index.html /home/ec2-user/app/
      - sudo cp -r scripts /home/ec2-user/app/ || echo "No scripts folder found, skipping..."
      - echo "Deployment preparation completed!"

  deploy:
    commands:
      - echo "Restarting application..."
      - sudo chmod +x /home/ec2-user/app/scripts/start.sh || echo "No start script found, skipping..."
      - sudo /home/ec2-user/app/scripts/start.sh || echo "Application started manually."
      - echo "Deployment completed successfully!"

artifacts:
  files:
    - index.html
    - scripts/** 