version: 0.2

phases:
  install:
    commands:
      - echo "Installing Apache HTTP Server..."
      - yum install -y httpd

  build:
    commands:
      - echo "Build phase - No compilation required"

  post_build:
    commands:
      - echo "Stopping any running Apache service..."
      - isExistApp=$(pgrep httpd)
      - if [[ -n "$isExistApp" ]]; then service httpd stop; fi
      - echo "Starting Apache service..."
      - service httpd start
      - echo "Packaging application..."
      - zip -r app.zip index.html scripts/ appspec.yml
      - aws s3 cp app.zip s3://my-new-backt/

artifacts:
  files:
    - app.zip